{% set version = "1.6.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-logicreg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/LogicReg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/LogicReg/LogicReg_{{ version }}.tar.gz
  sha256: 94d6aef83e8d1e5f010f29d3f2d1832cb758c152f4715923025d9327f8d7bfa3

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-survival
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-survival

test:
  commands:
    - $R -e "library('LogicReg')"           # [not win]
    - "\"%R%\" -e \"library('LogicReg')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=LogicReg
  license: GPL-2.0-or-later
  summary: Routines for fitting Logic Regression models. Logic Regression is described in Ruczinski, Kooperberg, and LeBlanc (2003) <DOI:10.1198/1061860032238>. Monte Carlo Logic Regression is described in and Kooperberg and Ruczinski (2005) <DOI:10.1002/gepi.20042>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: LogicReg
# Version: 1.5.12
# Date: 2019-06-17
# Title: Logic Regression
# Author: Charles Kooperberg <clk@fredhutch.org> and Ingo Ruczinski <ingo@jhu.edu>
# Maintainer: Charles Kooperberg <clk@fredhutch.org>
# Depends: R (>= 2.10), survival
# Imports: stats, graphics, utils, grDevices
# Description: Routines for fitting Logic Regression models. Logic Regression is described in Ruczinski, Kooperberg, and LeBlanc (2003) <DOI:10.1198/1061860032238>. Monte Carlo Logic Regression is described in and Kooperberg and Ruczinski (2005) <DOI:10.1002/gepi.20042>.
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2019-06-17 23:30:55 UTC; clk
# Repository: CRAN
# Date/Publication: 2019-06-18 21:52:03 UTC
