appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: C1581bAAO1ypkZ4y5G+7WfrwjXl0ZyCiwx3xPab6/eVbXZ9eVFoVkaPsgnJDU0hsOfgiKSzBi0VEywGU8acLKU3zynQ9sqqbGUKfw3SGoglQLDrYUaFf5NcAvAqNeifq/vRAePfZJ91FieUa0v72mETsAwXsqtBMh4ElNzERsQa5q8+Xwx6zz4qv/MoK8iL0H/sYtfYREXZoALnjcFD/uF3dQeiYHzMgqbQQeU0IfOM/3bxwiH7d39owjTYMf0Skv7Xbz2Bat3X21dsPy80vxFT+UjLSjmK4mH+ov3/afpbHim7TpBgAolme0pg5iKQlWPW3BD2gvUXZKOeHoyB/Csa5VGSU7YECOS2Tnjx6olRQpyWk5azPACSymVuXNSFjwEP5LlawwsajLS6gocwBmNUl247hbZP/dzUY+jiPDYpOQTGGBCTNuByixYdC4lPDxOiL3n54RgQAg7ewloFRsTWmB4pID8eAvKLt5X5kvhMTiRUtoswofTgRixwYeHLlnjj3FZ/u9KvXY5tvWzeNcwhwyfoC/Df5ifgRSTSum0D8D6C+GdTjgKy8nP2ZQwvwMCtlnRrInvM9CyyCHpAwqbd2vT95dds7HFF/BW7GQ5rFEYOj7MvsfrnOLJgk3mOXqiXDY3OgZME38Y8VE6Hx1nw2g0c7sIN6g+EaY+DRXZA=
